/// <reference types="react" />
declare const _default: {
    title: string;
};
export default _default;
export declare const _Conditional: () => JSX.Element;
export declare const _Arrow: () => JSX.Element;
export declare const _ArrowIcon: () => JSX.Element;
export declare const _DownArrow: () => JSX.Element;
export declare const _DownArrowIcon: () => JSX.Element;
export declare const _LeftArrow: () => JSX.Element;
export declare const _LeftArrowIcon: () => JSX.Element;
export declare const _RightArrow: () => JSX.Element;
export declare const _RightArrowIcon: () => JSX.Element;
export declare const _UpArrow: () => JSX.Element;
export declare const _UpArrowIcon: () => JSX.Element;
export declare const _HorizontalArrow: () => JSX.Element;
export declare const _HorizontalArrowIcon: () => JSX.Element;
export declare const _VerticalArrow: () => JSX.Element;
export declare const _VerticalArrowIcon: () => JSX.Element;
export declare const _Beehive: () => JSX.Element;
export declare const _BeehiveIcon: () => JSX.Element;
export declare const _Check: () => JSX.Element;
export declare const _CheckIcon: () => JSX.Element;
export declare const _Chevron: () => JSX.Element;
export declare const _ChevronIcon: () => JSX.Element;
export declare const _DownChevron: () => JSX.Element;
export declare const _DownChevronIcon: () => JSX.Element;
export declare const _LeftChevron: () => JSX.Element;
export declare const _LeftChevronIcon: () => JSX.Element;
export declare const _RightChevron: () => JSX.Element;
export declare const _RightChevronIcon: () => JSX.Element;
export declare const _UpChevron: () => JSX.Element;
export declare const _UpChevronIcon: () => JSX.Element;
export declare const _Close: () => JSX.Element;
export declare const _CloseIcon: () => JSX.Element;
export declare const _Hamburger: () => JSX.Element;
export declare const _HamburgerIcon: () => JSX.Element;
export declare const _HamburgerAlt: () => JSX.Element;
export declare const _HamburgerAltIcon: () => JSX.Element;
export declare const _HamburgerAltReverse: () => JSX.Element;
export declare const _HamburgerAltReverseIcon: () => JSX.Element;
export declare const _Plus: () => JSX.Element;
export declare const _PlusIcon: () => JSX.Element;
